/** A genre/style tag from Last.fm */
export interface Tag {
  /** PRIMARY KEY — deterministic hash of normalized name */
  id: string;
  /** Unique tag name, e.g. "post-metal" */
  name: string;
  /** last.fm tag page, e.g. "https://www.last.fm/tag/post-metal" */
  url: string;
}

/** A user of the bandmap application */
export interface User {
  /** PRIMARY KEY — UUIDv4 generated by the application */
  id: string;
  /** Unique username chosen by the user */
  username: string;
  /** Whether the user currently has administrator privileges via Cognito group membership */
  isAdmin: boolean;
  /** Cognito subject used as the auth linkage */
  cognitoSub: string;
  /** Unix epoch seconds */
  createdAt: number;
}

/** Invitation code for account creation */
export interface Invite {
  /** PRIMARY KEY — random invite code */
  code: string;
  /** UUIDv4 user id of the admin that created the invite */
  createdBy: string;
  /** Unix epoch seconds */
  createdAt: number;
  /** Unix epoch seconds — also used as DynamoDB TTL attribute */
  expiresAt: number;
  /** Maximum number of users that can redeem this code */
  maxUses: number;
  /** Number of successful redemptions */
  usedCount: number;
}

/** Core artist record — pull-through cache of Last.fm artist.getInfo */
export interface Artist {
  /** PRIMARY KEY — UUIDv4 surrogate artist ID */
  artistId: string;
  name: string;
  /** Last.fm artist page — unique Last.fm identifier (always present) */
  lastFmUrl: string;
  /** tag names, e.g. ["post-metal", "sludge"]; undefined when not yet fetched from Last.fm */
  tags?: string[];
  /** Unix epoch seconds of last fetch from Last.fm */
  fetchedAt: number;
  /** MusicBrainz ID (optional — not always available from Last.fm) */
  mbid?: string;
  /** Spotify artist URL (optional — resolved from MusicBrainz) */
  spotifyUrl?: string;
}

/**
 * A related-artist record — pull-through cache of artist.getSimilar.
 * "source is similar to target with score match."
 * Note: Last.fm similarity is NOT symmetric — A→B may differ from B→A.
 */
export interface RelatedArtist {
  /** PK — FK → Artist.artistId (the artist we queried) */
  sourceId: string;
  /** SK — FK → Artist.artistId (a similar artist) */
  targetId: string;
  /** denormalized — target may not be in the artists table yet */
  targetName: string;
  /** Last.fm URL of the target artist */
  targetLastFmUrl: string;
  /** 0.0–1.0 similarity score. 1.0 is very similar. */
  match: number;
  /** Unix epoch seconds of last fetch */
  fetchedAt: number;
}

/** A user's rating on an artist — star score and/or todo bookmark are independent */
export interface Rating {
  /** PK — FK → User.id */
  userId: string;
  /** SK — FK → Artist.artistId */
  artistId: string;
  /** 1–5 star rating; null when the artist has not been rated */
  score: number | null;
  /** Whether the artist is bookmarked for later listening; independent of score */
  todo: boolean;
  /** Unix epoch seconds */
  updatedAt: number;
}

/** A recommended artist for a user */
export interface Recommendation {
  /** PK — FK → User.id */
  userId: string;
  /** SK — FK → Artist.artistId */
  artistId: string;
  /** denormalized artist name for display */
  artistName: string;
  /** computed relevance score (higher = more relevant) */
  score: number;
  /** the liked artist that led to this recommendation */
  sourceId: string;
  /** denormalized source artist name */
  sourceName: string;
  /** Unix epoch seconds */
  generatedAt: number;
}
