name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npm run clean

      - run: npm run build

      - run: npm run lint

      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      FRONTEND_FQDN: ${{ secrets.FRONTEND_FQDN }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      FRONTEND_CERTIFICATE_ARN: ${{ secrets.FRONTEND_CERTIFICATE_ARN }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: npm ci

      - name: Write deployment environment
        run: |
          cat <<EOF > .env
          LASTFM_API_KEY=${LASTFM_API_KEY}
          AWS_REGION=${AWS_REGION}
          AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
          FRONTEND_FQDN=${FRONTEND_FQDN}
          HOSTED_ZONE_ID=${HOSTED_ZONE_ID}
          HOSTED_ZONE_NAME=${HOSTED_ZONE_NAME}
          FRONTEND_CERTIFICATE_ARN=${FRONTEND_CERTIFICATE_ARN}
          EOF

      - run: npm run deploy:backend

      - run: npm run deploy:frontend

      - run: npm run deploy:assets
